### ISSUE TITLE
There is no indentation between the equals sign and the matrix

### ISSUE THREAD

**Issue by vladtimss** [Mathpix/mathpix-markdown-it#338]
Hi
Could you fix or give some advice how fix such case. As we can see on the img there is no indention before matrix and after equals sign. On the other hand i could fix it via styles, but it can influence on other equations and we can face with unwantend behavior 

```css
.math-block {
        .MathJax {
            svg {
                g {
                    [data-mml-node='math'] > [data-mml-node='mtable'] {
                        transform: translate(130em, 0);
                    }
                }
            }
        }
    }
```

[
<img width="1378" alt="Снимок экрана 2024-07-19 в 10 38 07" src="https://github.com/user-attachments/assets/9e7a840b-f0d7-49a2-b8f3-59510a823fa5">
](url)
